[package]
name = "demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zmq = "0.9.2"
rmp-serde = "1.0.0"
serde = "1.0.136"
serde_derive = "1.0.136"

[features]
vendored-zmq = ['zmq/vendored']
